name: Run Python Script Daily

on:
  schedule:
    - cron: '0/10 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest    

    steps:
    - uses: actions/checkout@v2 
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install requests
      run: pip3 install requests
    - name: Run script    
      run: python3 ./arxiv_script.py   




    

